swagger: "2.0"
info:
  description: |
    API Description
  version: "1.0"
  title: API Title
  contact:
    name: artz1994@mail.ru
basePath: /
schemes:
  - http
  - https
paths:
  /ping_server:
    get:
      tags:
      - Ping
      summary: Ping Server
      description: Check if server available
      produces:
      - application/json
      responses:
        "200":
          description: successful operation

  /auth:
    get:
      tags:
      - auth_user
      summary: Authorization user
      description: This can only be done by the logged in user.
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Created aiohttp.BasicAuth
        required: true

      responses:
        "200":
          description: successful operation
        "401":
          description: Authorization failed